language: python
matrix:
  include:
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  - python: "3.8-dev" # 3.8 development branch
    dist: xenial
    sudo: true
  - python: "nightly"
  # command to install dependencies.
install:
  - sudo apt-get install python-matplotlib
  - pip install sphinx
  - python setup.py install
  - pip install coveralls
script: 
  - python3 -m unittest discover
  - python3 -m unittest pydlm/tests/tuner/test*.py
  - coverage run --source . -m unittest discover
after_success: coveralls
